---
Kb8Context:
  cluster: dsp-dev
  user: formsso.ci
  namespace: drt-dev


Fn::FileData:
- name: tls_tag
  files:
  - ../../artefacts/tls_tag
- name: app_tag
  files:
  - ../../artefacts/app_tag
- name: access_key
  encode: base64
  files:
  - ../secrets/dev/access_key
- name: secret_key
  encode: base64
  files:
  - ../secrets/dev/secret_key

APP_HTTP_PORT: 30271
APP_HTTPS_PORT: 30272
