apiVersion: v1
kind: ReplicationController
metadata:
  name: app
spec:
  replicas: 1
  selector:
    name: app
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
      - name: tls
        image: ${tls_tag}
        imagePullPolicy: Always
        ports:
        - containerPort: 443
        - containerPort: 80
        env:
        - name: LOAD_BALANCER_CIDR
          value: '10.50.0.0/22'
        - name: PROXY_SERVICE_HOST
          value: 127.0.0.1
        - name: PROXY_SERVICE_PORT
          value: "8080"
        - name: ENABLE_UUID_PARAM
          value: "FALSE"
        - name: NAXSI_USE_DEFAULT_RULES
          value: "FALSE"
        volumeMounts:
          - name: external-tls
            mountPath: /etc/keys
            readOnly: true
      - name: app
        image: ${app_tag}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      volumes:
        - name: external-tls
          secret:
            secretName: external-tls
