apiVersion: v1
kind: Service
metadata:
 labels:
   name: app
 name: app
spec:
 type: NodePort
 ports:
   - name: http
     port: 80
     targetPort: 8080
     nodePort: ${APP_HTTP_PORT}
   - name: https
     port: 443
     targetPort: 443
     nodePort: ${APP_HTTPS_PORT}
 selector:
   name: app
